# GLOBAL STUFF
experiment_id: stage_b_3b_finetuning # Name of your project
checkpoint_path: "E:\\checkpoint" # Checkpoint output
output_path: "E:\\output" # Sample Output (I don't know how this work, the output is generated jpg files)
model_version: 3B

# WandB
wandb_project: StableCascade
wandb_entity: wandb_username

# TRAINING PARAMS
lr: 1.0e-4
batch_size: 256
image_size: 1024
# multi_aspect_ratio: [1/1, 1/2, 1/3, 2/3, 3/4, 1/5, 2/5, 3/5, 4/5, 1/6, 5/6, 9/16]
shift: 4
grad_accum_steps: 1
updates: 100000
backup_every: 20000
save_every: 1000
warmup_updates: 1
use_fsdp: False

# GDF
#adaptive_loss_weight: True

# ema_start_iters: 5000
# ema_iters: 100
# ema_beta: 0.9

webdataset_path: "file:E:/yourfiles.tar" #assuming you are using local files. Amazon S3 maybe disabled in this script
effnet_checkpoint_path: "E:\\effnet_encoder.safetensors"
stage_a_checkpoint_path: "E:\\stage_a.safetensors"
generator_checkpoint_path: "E:\\stage_b_bf16.safetensors"
